import { useMemo, useState } from 'react';
import type { CitationExample, OwnedPage, QueryWorkbenchItem, ReportBundle } from '../types/report';
import { Badge, Card, SectionTitle } from './ui';

const unique = (values: string[]) => Array.from(new Set(values.filter(Boolean))).sort();
const label = (value = '') => value.replaceAll('_', ' ');
const statusTone = (value = '') => value.includes('external') || value.includes('competitor') ? 'high' : value.includes('owned_domain') ? 'medium' : value.includes('target') ? 'low' : 'neutral';

function sourceTypes(row: QueryWorkbenchItem) {
  return Array.from(new Set([...(row.external_top3_benchmark ?? []).map((c) => c.sourceType), ...(row.winning_patterns ?? []).map((p) => p.source_type ?? '')].filter(Boolean))).slice(0, 5);
}

function leadingDomain(row: QueryWorkbenchItem) {
  return (row.external_top3_benchmark ?? []).find((c) => c.domain)?.domain
    || (row.current_ai_visibility?.top_citations ?? []).find((c) => c.domain)?.domain
    || 'Not supplied';
}

function normaliseUrl(value: string | undefined) {
  return String(value || '').trim().replace(/#.*$/, '').replace(/\/$/, '').toLowerCase();
}

function citationRows(row: QueryWorkbenchItem): CitationExample[] {
  return row.winning_patterns?.length
    ? []
    : [...(row.external_top3_benchmark ?? []), ...(row.current_ai_visibility?.top_citations ?? [])];
}

type MappedOwnedUrl = NonNullable<QueryWorkbenchItem['mapped_owned_urls']>[number];

function jsonLdStatus(item: MappedOwnedUrl, owned?: OwnedPage) {
  const tech = owned?.technicalSignals;
  const direct = item as Record<string, unknown>;
  const present = tech?.jsonLdPresent ?? direct.json_ld_present ?? direct.jsonLdPresent;
  const schemaTypes = tech?.schemaTypes ?? [];
  if (present === undefined || present === null) return 'JSON-LD: not checked';
  if (present === false) return 'JSON-LD: missing';
  return schemaTypes.length <= 1 ? 'JSON-LD: partial' : 'JSON-LD: present';
}

export function QueryWorkbench({ report }: { report: ReportBundle }) {
  const rows = useMemo(() => report.queryWorkbench ?? [], [report.queryWorkbench]);
  const [search, setSearch] = useState('');
  const [journey, setJourney] = useState('All');
  const [status, setStatus] = useState('All');
  const [sortBy, setSortBy] = useState('value');
  const [visibleCount, setVisibleCount] = useState(12);

  const journeys = useMemo(() => unique(rows.map((row) => row.journey_category ?? 'Unclassified')), [rows]);
  const statuses = useMemo(() => unique(rows.map((row) => row.current_ai_visibility?.status ?? 'not_observed')), [rows]);

  const filtered = useMemo(() => {
    const term = search.trim().toLowerCase();
    const priorityWeight = (row: QueryWorkbenchItem) => {
      const score = row.current_ai_visibility?.score ?? 0;
      const externalCount = row.external_top3_benchmark?.length ?? 0;
      const competitorCount = row.current_ai_visibility?.competitor_citation_count ?? 0;
      return (100 - score) + externalCount * 5 + competitorCount * 10;
    };
    return rows.filter((row) => {
      const haystack = [
        row.query_id,
        row.query,
        row.journey_category,
        row.current_ai_visibility?.status,
        ...(row.current_ai_visibility?.competitors ?? []),
        leadingDomain(row),
        ...sourceTypes(row),
        ...(row.mapped_owned_urls ?? []).map((u) => `${u.url} ${u.title}`),
        ...(row.winning_patterns ?? []).map((p) => `${p.source_domain} ${p.pattern_type}`)
      ].join(' ').toLowerCase();
      return (!term || haystack.includes(term))
        && (journey === 'All' || row.journey_category === journey)
        && (status === 'All' || row.current_ai_visibility?.status === status);
    }).sort((a, b) => {
      if (sortBy === 'visibility_asc') return (a.current_ai_visibility?.score ?? 0) - (b.current_ai_visibility?.score ?? 0);
      if (sortBy === 'visibility_desc') return (b.current_ai_visibility?.score ?? 0) - (a.current_ai_visibility?.score ?? 0);
      if (sortBy === 'external_desc') return (b.external_top3_benchmark?.length ?? 0) - (a.external_top3_benchmark?.length ?? 0);
      if (sortBy === 'competitor_desc') return (b.current_ai_visibility?.competitor_citation_count ?? 0) - (a.current_ai_visibility?.competitor_citation_count ?? 0);
      return priorityWeight(b) - priorityWeight(a);
    });
  }, [rows, search, journey, status, sortBy]);

  if (!rows.length) {
    return <Card><SectionTitle eyebrow="Query workbench" title="No canonical query_workbench[] found">Upload a frontend_report_bundle generated by the current AIVisibilityAuditor orchestration.</SectionTitle></Card>;
  }

  const visible = filtered.slice(0, visibleCount);

  return (
    <Card>
      <SectionTitle eyebrow="Query workbench" title={`Closed-loop query optimisation view (${filtered.length}/${rows.length})`}>
        Query diagnostics and workbench are combined here. Each card shows {report.brand || 'brand'} AI visibility, competitor names, winning source types, leading citation domain and mapped owned URLs.
      </SectionTitle>
      <div className="mb-5 grid gap-3 md:grid-cols-2 lg:grid-cols-4">
        <input className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm" placeholder="Search query, URL, domain, competitor..." value={search} onChange={(event) => { setSearch(event.target.value); setVisibleCount(12); }} />
        <select className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm" value={journey} onChange={(event) => { setJourney(event.target.value); setVisibleCount(12); }}>
          <option>All</option>{journeys.map((item) => <option key={item}>{item}</option>)}
        </select>
        <select className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm" value={status} onChange={(event) => { setStatus(event.target.value); setVisibleCount(12); }}>
          <option>All</option>{statuses.map((item) => <option key={item}>{item}</option>)}
        </select>
        <select className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm" value={sortBy} onChange={(event) => setSortBy(event.target.value)}>
          <option value="value">Sort: highest intervention value</option>
          <option value="visibility_asc">Sort: lowest {report.brand || 'brand'} visibility</option>
          <option value="visibility_desc">Sort: highest {report.brand || 'brand'} visibility</option>
          <option value="external_desc">Sort: most external citations</option>
          <option value="competitor_desc">Sort: most competitor citations</option>
        </select>
      </div>
      <div className="grid gap-4 md:grid-cols-2">
        {visible.map((row) => <WorkbenchCard key={row.query_id} row={row} ownedPages={report.ownedPages} />)}
      </div>
      {visibleCount < filtered.length ? (
        <div className="mt-5 flex justify-center">
          <button className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700" onClick={() => setVisibleCount((count) => count + 12)}>Show more queries</button>
        </div>
      ) : null}
    </Card>
  );
}

function WorkbenchCard({ row, ownedPages }: { row: QueryWorkbenchItem; ownedPages: OwnedPage[] }) {
  const vis = row.current_ai_visibility ?? {};
  const mapped = row.mapped_owned_urls ?? [];
  const competitors = (vis.competitors ?? []).join(', ');
  const types = sourceTypes(row).map(label).join(', ') || 'Not supplied';
  const ownedByUrl = new Map(ownedPages.map((page) => [normaliseUrl(page.url), page]));
  const fallbackCitations = citationRows(row);
  const showCompetitors = competitors || (vis.competitor_citation_count ?? 0) > 0 || String(vis.status || '').includes('competitor');
  return (
    <article className="rounded-2xl border border-slate-200 bg-slate-50 p-4">
      <div className="flex items-start justify-between gap-3">
        <div>
          <p className="text-xs font-bold uppercase tracking-[0.18em] text-slate-500">{row.query_id} · {row.journey_category || 'Unclassified'}</p>
          <h3 className="mt-2 text-base font-semibold leading-6 text-slate-950">{row.query}</h3>
        </div>
        <div className="flex shrink-0 flex-col items-end gap-2">
          <span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-slate-700">{vis.score ?? 0}/100</span>
          <Badge tone={statusTone(vis.status)}>{label(vis.status || 'n/a')}</Badge>
        </div>
      </div>
      <div className="mt-4 grid grid-cols-1 gap-3 text-sm md:grid-cols-3">
        {showCompetitors && <Metric label="Competitors" value={competitors || `${vis.competitor_citation_count ?? 0} competitor citations`} />}
        <Metric label="Winning source types" value={types} />
        <Metric label="Leading citation domain" value={leadingDomain(row)} />
      </div>
      <details className="mt-4 rounded-xl bg-white p-3">
        <summary className="cursor-pointer font-semibold text-slate-900">Top mapped owned URLs ({mapped.length})</summary>
        <ol className="mt-2 list-decimal space-y-2 pl-5 text-sm text-slate-700">
          {mapped.map((item) => {
            const owned = ownedByUrl.get(normaliseUrl(item.url));
            return <li key={item.url}><span className="font-semibold text-slate-950">{item.title || item.url}</span><br /><span className="break-all text-xs text-slate-500">{item.url}</span><br />GEO: {item.current_geo_score_120 ?? owned?.geoScore ?? 0}/120 · {jsonLdStatus(item, owned)}</li>;
          })}
        </ol>
      </details>
      <details className="mt-3 rounded-xl bg-white p-3">
        <summary className="cursor-pointer font-semibold text-slate-900">Winning patterns ({row.winning_patterns?.length ?? fallbackCitations.length})</summary>
        <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-700">
          {(row.winning_patterns ?? []).map((pattern, idx) => <li key={`${pattern.source_url}-${idx}`}><span className="font-semibold">{label(pattern.pattern_type || '')}</span>{pattern.source_domain ? ` · ${pattern.source_domain}` : ''}{pattern.evidence_basis ? ` - ${pattern.evidence_basis}` : ''}</li>)}
          {!row.winning_patterns?.length && fallbackCitations.map((citation, idx) => <li key={`${citation.url}-${idx}`}><span className="font-semibold">{citation.domain || citation.url || 'Citation source'}</span>{citation.sourceType ? ` · ${label(citation.sourceType)}` : ''}{citation.snippet ? ` - ${citation.snippet}` : ''}</li>)}
          {!row.winning_patterns?.length && !fallbackCitations.length ? <li>No citation evidence supplied for this query.</li> : null}
        </ul>
      </details>
    </article>
  );
}

function Metric({ label, value }: { label: string; value: string }) {
  return <div><p className="text-slate-500">{label}</p><p className="font-semibold text-slate-900">{value}</p></div>;
}
