import { useEffect, useMemo, useState } from 'react';
import type { CitationExample, OwnedPage, QueryWorkbenchItem, ReportBundle } from '../types/report';
import { Badge, StatusPill, WorkspacePanel, SectionHeader, MetricPill } from './ui';

const unique = (values: string[]) => Array.from(new Set(values.filter(Boolean))).sort();
const label = (value = '') => value.replaceAll('_', ' ');

function sourceTypes(row: QueryWorkbenchItem) {
  return Array.from(new Set([...(row.external_top3_benchmark ?? []).map((c) => c.sourceType), ...(row.winning_patterns ?? []).map((p) => p.source_type ?? '')].filter(Boolean))).slice(0, 5);
}

function leadingDomain(row: QueryWorkbenchItem) {
  return (row.external_top3_benchmark ?? []).find((c) => c.domain)?.domain
    || (row.current_ai_visibility?.top_citations ?? []).find((c) => c.domain)?.domain
    || 'Not supplied';
}

function normaliseUrl(value: string | undefined) {
  return String(value || '').trim().replace(/#.*$/, '').replace(/\/$/, '').toLowerCase();
}

function citationRows(row: QueryWorkbenchItem): CitationExample[] {
  return row.winning_patterns?.length
    ? []
    : [...(row.external_top3_benchmark ?? []), ...(row.current_ai_visibility?.top_citations ?? [])];
}

type MappedOwnedUrl = NonNullable<QueryWorkbenchItem['mapped_owned_urls']>[number];

function jsonLdStatus(item: MappedOwnedUrl, owned?: OwnedPage) {
  const tech = owned?.technicalSignals;
  const direct = item as Record<string, unknown>;
  const present = tech?.jsonLdPresent ?? direct.json_ld_present ?? direct.jsonLdPresent;
  const schemaTypes = tech?.schemaTypes ?? [];
  if (present === undefined || present === null) return 'JSON-LD: not checked';
  if (present === false) return 'JSON-LD: missing';
  return schemaTypes.length <= 1 ? 'JSON-LD: partial' : 'JSON-LD: present';
}

export function QueryWorkbench({ report }: { report: ReportBundle }) {
  const rows = useMemo(() => report.queryWorkbench ?? [], [report.queryWorkbench]);
  const [search, setSearch] = useState('');
  const [journey, setJourney] = useState('All');
  const [status, setStatus] = useState('All');
  const [sortBy, setSortBy] = useState('value');
  const [cardPage, setCardPage] = useState(0);
  const CARDS_PER_PAGE = 4;

  const journeys = useMemo(() => unique(rows.map((row) => row.journey_category ?? 'Unclassified')), [rows]);
  const statuses = useMemo(() => unique(rows.map((row) => row.current_ai_visibility?.status ?? 'not_observed')), [rows]);

  const filtered = useMemo(() => {
    const term = search.trim().toLowerCase();
    const priorityWeight = (row: QueryWorkbenchItem) => {
      const score = row.current_ai_visibility?.score ?? 0;
      const externalCount = row.external_top3_benchmark?.length ?? 0;
      const competitorCount = row.current_ai_visibility?.competitor_citation_count ?? 0;
      return (100 - score) + externalCount * 5 + competitorCount * 10;
    };
    return rows.filter((row) => {
      const haystack = [
        row.query_id, row.query, row.journey_category, row.current_ai_visibility?.status,
        ...(row.current_ai_visibility?.competitors ?? []), leadingDomain(row), ...sourceTypes(row),
        ...(row.mapped_owned_urls ?? []).map((u) => `${u.url} ${u.title}`),
        ...(row.winning_patterns ?? []).map((p) => `${p.source_domain} ${p.pattern_type}`)
      ].join(' ').toLowerCase();
      return (!term || haystack.includes(term))
        && (journey === 'All' || row.journey_category === journey)
        && (status === 'All' || row.current_ai_visibility?.status === status);
    }).sort((a, b) => {
      if (sortBy === 'visibility_asc') return (a.current_ai_visibility?.score ?? 0) - (b.current_ai_visibility?.score ?? 0);
      if (sortBy === 'visibility_desc') return (b.current_ai_visibility?.score ?? 0) - (a.current_ai_visibility?.score ?? 0);
      if (sortBy === 'external_desc') return (b.external_top3_benchmark?.length ?? 0) - (a.external_top3_benchmark?.length ?? 0);
      if (sortBy === 'competitor_desc') return (b.current_ai_visibility?.competitor_citation_count ?? 0) - (a.current_ai_visibility?.competitor_citation_count ?? 0);
      return priorityWeight(b) - priorityWeight(a);
    });
  }, [rows, search, journey, status, sortBy]);

  // Reset page when filters change
  useEffect(() => { setCardPage(0); }, [search, journey, status, sortBy]);

  const totalCardPages = Math.ceil(filtered.length / CARDS_PER_PAGE);
  const pagedCards = filtered.slice(cardPage * CARDS_PER_PAGE, (cardPage + 1) * CARDS_PER_PAGE);

  if (!rows.length) {
    return <WorkspacePanel><SectionHeader eyebrow="Query workbench" title="No canonical query_workbench[] found">Upload a frontend_report_bundle generated by the current AIVisibilityAuditor orchestration.</SectionHeader></WorkspacePanel>;
  }

  return (
    <WorkspacePanel>
      <SectionHeader eyebrow="Query workbench" title={`Closed-loop query optimisation view (${filtered.length}/${rows.length})`}>
        Each card shows brand AI visibility, competitor names, winning source types, leading citation domain and mapped owned URLs.
      </SectionHeader>
      <div className="mb-5 grid gap-3 md:grid-cols-2 lg:grid-cols-4">
        <input className="rounded-[var(--radius-sm)] border border-[var(--border-subtle)] bg-[var(--bg-card)] px-3 py-2 text-sm text-[var(--text-primary)]" placeholder="Search query, URL, domain\u2026" value={search} onChange={(event) => { setSearch(event.target.value); setCardPage(0); }} />
        <select className="rounded-[var(--radius-sm)] border border-[var(--border-subtle)] bg-[var(--bg-card)] px-3 py-2 text-sm text-[var(--text-primary)]" value={journey} onChange={(event) => { setJourney(event.target.value); setCardPage(0); }}>
          <option>All</option>{journeys.map((item) => <option key={item}>{item}</option>)}
        </select>
        <select className="rounded-[var(--radius-sm)] border border-[var(--border-subtle)] bg-[var(--bg-card)] px-3 py-2 text-sm text-[var(--text-primary)]" value={status} onChange={(event) => { setStatus(event.target.value); setCardPage(0); }}>
          <option>All</option>{statuses.map((item) => <option key={item}>{item}</option>)}
        </select>
        <select className="rounded-[var(--radius-sm)] border border-[var(--border-subtle)] bg-[var(--bg-card)] px-3 py-2 text-sm text-[var(--text-primary)]" value={sortBy} onChange={(event) => setSortBy(event.target.value)}>
          <option value="value">Sort: highest intervention value</option>
          <option value="visibility_asc">Sort: lowest brand visibility</option>
          <option value="visibility_desc">Sort: highest brand visibility</option>
          <option value="external_desc">Sort: most external citations</option>
          <option value="competitor_desc">Sort: most competitor citations</option>
        </select>
      </div>
      <div className="grid gap-4 md:grid-cols-2">
        {pagedCards.map((row) => <WorkbenchCard key={row.query_id} row={row} ownedPages={report.ownedPages} />)}
      </div>
      {/* Pagination controls */}
      {totalCardPages > 1 && (
        <div className="mt-5 flex items-center justify-between">
          <p className="text-xs text-[var(--text-muted)]">
            Showing {cardPage * CARDS_PER_PAGE + 1}\u2013{Math.min((cardPage + 1) * CARDS_PER_PAGE, filtered.length)} of {filtered.length} queries
          </p>
          <div className="flex items-center gap-2">
            <button className="rounded-[var(--radius-sm)] border border-[var(--border-subtle)] bg-[var(--bg-card)] px-3 py-1.5 text-xs font-semibold text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:border-[var(--border-strong)] disabled:opacity-40" onClick={() => setCardPage((p) => Math.max(0, p - 1))} disabled={cardPage === 0}>Previous</button>
            <span className="text-xs text-[var(--text-secondary)]">{cardPage + 1} / {totalCardPages}</span>
            <button className="rounded-[var(--radius-sm)] border border-[var(--border-subtle)] bg-[var(--bg-card)] px-3 py-1.5 text-xs font-semibold text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:border-[var(--border-strong)] disabled:opacity-40" onClick={() => setCardPage((p) => Math.min(totalCardPages - 1, p + 1))} disabled={cardPage >= totalCardPages - 1}>Next</button>
          </div>
        </div>
      )}
      {!filtered.length && <p className="mt-4 text-sm text-[var(--text-muted)]">No queries match the current filters.</p>}
    </WorkspacePanel>
  );
}

function WorkbenchCard({ row, ownedPages }: { row: QueryWorkbenchItem; ownedPages: OwnedPage[] }) {
  const vis = row.current_ai_visibility ?? {};
  const mapped = row.mapped_owned_urls ?? [];
  const competitors = (vis.competitors ?? []).join(', ');
  const types = sourceTypes(row).map(label).join(', ') || 'Not supplied';
  const ownedByUrl = new Map(ownedPages.map((page) => [normaliseUrl(page.url), page]));
  const fallbackCitations = citationRows(row);
  const showCompetitors = competitors || (vis.competitor_citation_count ?? 0) > 0 || String(vis.status || '').includes('competitor');
  return (
    <article className="rounded-[var(--radius-md)] border border-[var(--border-subtle)] bg-[var(--bg-card)] p-4 hover:bg-[var(--bg-card-hover)] transition-colors">
      <div className="flex items-start justify-between gap-3">
        <div>
          <p className="typo-meta text-[var(--text-muted)]">{row.query_id} · {row.journey_category || 'Unclassified'}</p>
          <h3 className="mt-2 text-[15px] font-semibold leading-6 text-[var(--text-primary)]">{row.query}</h3>
        </div>
        <div className="flex shrink-0 flex-col items-end gap-2">
          <span className="rounded-full border border-[var(--border-subtle)] bg-[var(--bg-panel)] px-3 py-1 text-xs font-bold text-[var(--text-primary)]">{vis.score ?? 0}/100</span>
          <StatusPill status={vis.status || 'not_observed'} />
        </div>
      </div>
      {/* Sentiment tag */}
      <div className="mt-3">
        {vis.brand_mentioned ? (
          <span className={`inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-semibold ${
            vis.brand_sentiment === 'positive' ? 'bg-emerald-500/10 text-emerald-400 ring-1 ring-emerald-500/20' :
            vis.brand_sentiment === 'negative' ? 'bg-red-500/10 text-red-400 ring-1 ring-red-500/20' :
            vis.brand_sentiment === 'mixed' ? 'bg-amber-500/10 text-amber-300 ring-1 ring-amber-500/20' :
            'bg-white/5 text-[var(--text-muted)] ring-1 ring-white/10'
          }`}>
            Sentiment: {vis.brand_sentiment || 'neutral'}{vis.brand_sentiment_score != null ? ` (${vis.brand_sentiment_score > 0 ? '+' : ''}${vis.brand_sentiment_score})` : ''}
          </span>
        ) : (
          <span className="inline-flex rounded-full bg-white/5 px-3 py-1 text-xs font-semibold text-[var(--text-muted)] ring-1 ring-white/10">Sentiment: N/A</span>
        )}
      </div>
      <div className="mt-4 grid grid-cols-1 gap-3 text-sm md:grid-cols-3">
        {showCompetitors && <Metric label="Competitors" value={competitors || `${vis.competitor_citation_count ?? 0} competitor citations`} />}
        <Metric label="Winning source types" value={types} />
        <Metric label="Leading citation domain" value={leadingDomain(row)} />
      </div>
      <details className="mt-4 rounded-[var(--radius-sm)] border border-[var(--border-subtle)] bg-[var(--bg-panel)] p-3">
        <summary className="cursor-pointer font-semibold text-[var(--text-primary)] text-sm">Top mapped owned URLs ({mapped.length})</summary>
        <ol className="mt-2 list-decimal space-y-2 pl-5 text-sm text-[var(--text-secondary)]">
          {mapped.map((item) => {
            const owned = ownedByUrl.get(normaliseUrl(item.url));
            return <li key={item.url}><span className="font-semibold text-[var(--text-primary)]">{item.title || item.url}</span><br /><span className="break-all text-xs text-[var(--text-muted)]">{item.url}</span><br /><span className="text-xs">GEO: {item.current_geo_score_120 ?? owned?.geoScore ?? 0}/120 · {jsonLdStatus(item, owned)}</span></li>;
          })}
        </ol>
      </details>
      <details className="mt-3 rounded-[var(--radius-sm)] border border-[var(--border-subtle)] bg-[var(--bg-panel)] p-3">
        <summary className="cursor-pointer font-semibold text-[var(--text-primary)] text-sm">Winning patterns ({row.winning_patterns?.length ?? fallbackCitations.length})</summary>
        <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-[var(--text-secondary)]">
          {(row.winning_patterns ?? []).map((pattern, idx) => <li key={`${pattern.source_url}-${idx}`}><span className="font-semibold text-[var(--text-primary)]">{label(pattern.pattern_type || '')}</span>{pattern.source_domain ? ` · ${pattern.source_domain}` : ''}{pattern.evidence_basis ? ` - ${pattern.evidence_basis}` : ''}</li>)}
          {!row.winning_patterns?.length && fallbackCitations.map((citation, idx) => <li key={`${citation.url}-${idx}`}><span className="font-semibold text-[var(--text-primary)]">{citation.domain || citation.url || 'Citation source'}</span>{citation.sourceType ? ` · ${label(citation.sourceType)}` : ''}{citation.snippet ? ` - ${citation.snippet}` : ''}</li>)}
          {!row.winning_patterns?.length && !fallbackCitations.length ? <li>No citation evidence supplied for this query.</li> : null}
        </ul>
      </details>
    </article>
  );
}

function Metric({ label, value }: { label: string; value: string }) {
  return <div><p className="text-xs text-[var(--text-muted)]">{label}</p><p className="font-semibold text-[var(--text-primary)] text-sm">{value}</p></div>;
}
